swagger: "2.0"
info: 
  description: "The \"Dependency Monkey\" is a service for validating package dependencies within an application stack"
  version: "0.1.0"
  title: "Thoth: Dependency Monkey API"
responses: 
  ParseError:
    description: "When a mask can't be parsed"
  MaskError: 
    description: "When any error occurs on mask"
produces:
  - application/json
consumes: 
  - application/json
basePath: "/api/v0alpha0"
definitions: 
  
  Validation: 
    properties: 
      ecosystem: 
        description: "In which ecosystem is the stack specification to be validated: [pypi]"
        example: pypi
        type: string
      valid: 
        description: "This indicates that the Validation is valid"
        example: true
        type: boolean
      raw_log: 
        description: "This is the raw log of the Validation job"
        type: string
      phase: 
        description: "Phase of the Validation job: [pending, running, succeeded, failed]"
        example: succeeded
        type: string
      stack_specification: 
        description: "Specification of the Software Stack"
        example: "pandas\\nnumpy>=1.11.0"
        type: string
      id: 
        description: "The Validation unique identifier"
        example: "7b63d226-1d6c-11e8-968f-54ee7504b46f"
        type: string
    type: object
    required: 
      - ecosystem
      - id
      - phase
      - stack_specification
  
  ValidationListItem: 
    properties: 
      id: 
        description: "The Validation unique identifier"
        example: "7b63d226-1d6c-11e8-968f-54ee7504b46f"
        type: string
    type: object
    required: 
      - id
  
  ValidationRequest: 
    properties: 
      stack_specification: 
        description: "Specification of the Software Stack"
        example: "pandas\\nnumpy>=1.11.0"
        type: string
      ecosystem: 
        description: "In which ecosystem is the stack specification to be validated: [pypi]"
        default: pypi
        type: string
        type: object
        required: 
          - 
          ecosystem
          - 
          stack_specification

tags: []
  description: "Default namespace"
  name: default
  -
  description: Validations
  name: validations

paths:
  /validations:
    get: 
      parameters: 
        - name : X-Fields
          format: mask
          description: "An optional fields mask"
          in: header
          type: string
      tags: [validations]
      responses: 
        200:
          description: Success
          schema:
            $ref: "#/definitions/ValidationListItem"
        503: 
          description: "Service we depend on is not available"
      operationId: list_validations
      summary: "List all Validations"
    
    post: 
      parameters: 
        - name: payload
          schema: 
            $ref: "#/definitions/ValidationRequest"
          in: body
          required: true
        - name : X-Fields
          format: mask
          description: "An optional fields mask"
          in: header
          type: string
      tags: [validations]
      responses: 
        201: 
          description: Success
          schema: 
            $ref: "#/definitions/Validation"
        400: 
          description: "Ecosystem not supported"
        503: 
          description: "Service we depend on is not available"
      operationId: request_validation
      summary: "Request a new Validation"
  
  /validations/{id}: 
    get: 
      parameters: 
        - name : id
          in: path
          required: true
          type: string
          description: "The Validation identifier"
        - name : X-Fields 
          format: mask
          description: "An optional fields mask"
          in: header
          type: string
      tags: [validations]
      responses: 
        200: 
          description: Success
          schema: 
            $ref: "#/definitions/Validation"
        404: 
          description: "Validation not found"
      operationId: get_validation
      summary: "Show a specific Validation"
    delete: 
    tags: [validations]
    responses: 
      204: 
        description: "Validation deleted"
      404: 
        description: "Validation not found"
    operationId: delete_validation
    summary: "Delete a Validation given its identifier"
